spring:
  application:
    name: hello-server
    
server:
  port: 8071
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
      
  instance:
    hostname: localhost